on:
  push:
#    branches:
#      - 'main'
    paths:
      - pode/**
      - scripts/**
      - Dockerfile
  workflow_dispatch:      

name: "GitHub Build and Deploy"

jobs:
    build-push-and-deploy:
        runs-on: ubuntu-latest
        steps:

        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}    
        - run: |
            docker pull docker.io/badgerati/pode:latest      
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image to ACR'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ vars.CONTAINER_IMAGE_NAME }}:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ vars.CONTAINER_IMAGE_NAME }}:${{ github.sha }}

        - name: 'Build and deploy Container App'
          uses: azure/container-apps-deploy-action@v1
          with:
            acrName: ${{ secrets.REGISTRY_NAME }}
            containerAppName: ${{ secrets.CONTAINER_APP_NAME }}
            resourceGroup: ${{ secrets.RESOURCE_GROUP }}
            imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ vars.CONTAINER_IMAGE_NAME }}:${{ github.sha }}         